export const navigation = [
  { name: "Home", href: "#", current: true },
  { name: "Exercise", href: "#exercises", current: false },
  { name: "Workout Plan", href: "#", current: false },
  { name: "BMI", href: "#bmi", current: false },
];

export const bodyPart = [
  { id: 0, name: "All" },
  { id: 1, name: "back" },
  { id: 2, name: "cardio" },
  { id: 3, name: "chest" },
  { id: 4, name: "lower arms" },
  { id: 5, name: "lower legs" },
  { id: 6, name: "neck" },
  { id: 7, name: "shoulders" },
  { id: 8, name: "upper arms" },
  { id: 9, name: "upper legs" },
  { id: 10, name: "waist" },
];

export const exercises = [
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/tuOOr3i41qA6xL",
    id: "3294",
    name: "archer push up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/3EkKePcir7cZSP",
    id: "0009",
    name: "assisted chest dip (kneeling)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "assisted",
    gifUrl: "https://api.exercisedb.io/image/aGRb63KijBqxQD",
    id: "1716",
    name: "assisted seated pectoralis major stretch with stability ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/K7ymfGV3gYxwAa",
    id: "2364",
    name: "assisted wide-grip chest dip (kneeling)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "band",
    gifUrl: "https://api.exercisedb.io/image/q8-cxRITYtBvDT",
    id: "1254",
    name: "band bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "band",
    gifUrl: "https://api.exercisedb.io/image/NmI5MyzEJe-KR8",
    id: "0989",
    name: "band one arm twisting chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/iEcnPZc314IeMO",
    id: "0025",
    name: "barbell bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/towGEp93J6QQ2y",
    id: "0033",
    name: "barbell decline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/VFdwDOX9NWbYC4",
    id: "1255",
    name: "barbell decline pullover",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/zJqJU2o8uuYG1J",
    id: "0036",
    name: "barbell decline wide-grip press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/HsWy4baR5QYVtc",
    id: "0040",
    name: "barbell front raise and pullover",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/lAL8CB6soqfG7Z",
    id: "0045",
    name: "barbell guillotine bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/fiFwJRTLnmhRbB",
    id: "0047",
    name: "barbell incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/0JmBvSFw3GEy-9",
    id: "0050",
    name: "barbell incline shoulder raise",
    target: "serratus anterior",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/oThJF8etovfkqT",
    id: "1256",
    name: "barbell reverse grip decline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/e6vUQnWC0PLAxz",
    id: "1257",
    name: "barbell reverse grip incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/sCYND06CsX0CaV",
    id: "0122",
    name: "barbell wide bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/HhaBNUSHBcFpiC",
    id: "1258",
    name: "barbell wide reverse grip bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "assisted",
    gifUrl: "https://api.exercisedb.io/image/pXR2MGLemtS9tr",
    id: "1259",
    name: "behind head chest stretch",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/h0mYyCgLLfhZJY",
    id: "0151",
    name: "cable bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/lQWMz3yFXkIp1H",
    id: "0155",
    name: "cable cross-over variation",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/sb5un5Hp6UKyrt",
    id: "0158",
    name: "cable decline fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/Ye4pRljVrpeHh3",
    id: "1260",
    name: "cable decline one arm press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/HYI5e4a57nYHU8",
    id: "1261",
    name: "cable decline press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/uOS1G4qvjQsohP",
    id: "0169",
    name: "cable incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/WGhhKm4qOVPkkM",
    id: "0171",
    name: "cable incline fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/5rONE2qj-4kFhW",
    id: "0170",
    name: "cable incline fly (on stability ball)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/Gkkma2bUXlHjla",
    id: "0179",
    name: "cable low fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/OnRHTDvQNX1Ti4",
    id: "0185",
    name: "cable lying fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/DO1ieYH4KVTpoL",
    id: "0188",
    name: "cable middle fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/XFfSnHKgTIJna7",
    id: "1262",
    name: "cable one arm decline chest fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/PEACL9hk5JrovV",
    id: "1263",
    name: "cable one arm fly on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/69b9Itv1258k4P",
    id: "1264",
    name: "cable one arm incline fly on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/Pdu83AyYverjco",
    id: "1265",
    name: "cable one arm incline press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/OMMhr3pAY9Z3yz",
    id: "1266",
    name: "cable one arm incline press on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/hs96FRcABHoTbL",
    id: "0191",
    name: "cable one arm lateral bent-over",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/zLE2EMcqTBsP34",
    id: "1267",
    name: "cable one arm press on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/rC8HL0LHTpyZxa",
    id: "1268",
    name: "cable press on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/3oO8dSXKV9A958",
    id: "2144",
    name: "cable seated chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/eR6sYzx3uXRHP6",
    id: "0227",
    name: "cable standing fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/WdLqV6EWHcE6lp",
    id: "1269",
    name: "cable standing up straight crossovers",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "cable",
    gifUrl: "https://api.exercisedb.io/image/JaNol-jOHgcMwq",
    id: "1270",
    name: "cable upper chest crossovers",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/xxKsLeggAOOo32",
    id: "1271",
    name: "chest and front of shoulder stretch",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/Ett1DrFlVw0VWl",
    id: "0251",
    name: "chest dip",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/VPrcDZWiUwFd5A",
    id: "1430",
    name: "chest dip (on dip-pull-up cage)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/pS9aw023fEIayK",
    id: "2462",
    name: "chest dip on straight bar",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "stability ball",
    gifUrl: "https://api.exercisedb.io/image/KUhGGt8eb7EFsn",
    id: "1272",
    name: "chest stretch with exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/YzWkSuvNIKPz3g",
    id: "3216",
    name: "chest tap push-up (male)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/WwVtfR-0brTARS",
    id: "1273",
    name: "clap push up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/A5xToVDU4LozYn",
    id: "0258",
    name: "clock push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/j-TvKY3xnt0Pat",
    id: "0279",
    name: "decline push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/cc3UUtrko5nyIY",
    id: "1274",
    name: "deep push up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/6R89RyK3Fe31k-",
    id: "1275",
    name: "drop push up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/pxSkDTTK-GP0Hh",
    id: "0288",
    name: "dumbbell around pullover",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/FdG-N4OaykoXmK",
    id: "0289",
    name: "dumbbell bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/JpdxfbbouLu109",
    id: "0301",
    name: "dumbbell decline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/63IsVWHkDBxNjf",
    id: "0302",
    name: "dumbbell decline fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/lfF89Mqhdogq0o",
    id: "0303",
    name: "dumbbell decline hammer press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/AlIp-FMtOjThm2",
    id: "1276",
    name: "dumbbell decline one arm fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/sXYlK6Db4v-OV2",
    id: "0307",
    name: "dumbbell decline twist fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/TQ-T97XBCthRXq",
    id: "0308",
    name: "dumbbell fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/bmcu5jFnj5aT6q",
    id: "1277",
    name: "dumbbell fly on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/7Ad3NSE9k6ScmC",
    id: "3545",
    name: "dumbbell incline alternate press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/n2ZUtLi4xpnXmX",
    id: "0314",
    name: "dumbbell incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/xt9iK32cYxq3ah",
    id: "0316",
    name: "dumbbell incline breeding",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/HMfgKga3uh2JaZ",
    id: "0319",
    name: "dumbbell incline fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/HBXUsTRvTBaEKR",
    id: "1278",
    name: "dumbbell incline fly on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/F23h7MyK-B0FLa",
    id: "0321",
    name: "dumbbell incline hammer press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/n-reWlf0jzdc84",
    id: "1279",
    name: "dumbbell incline one arm fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/rnuqKdC0svHpb2",
    id: "1280",
    name: "dumbbell incline one arm fly on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/FQbxkvJpP4v7U-",
    id: "1281",
    name: "dumbbell incline one arm press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/mPjHcUnp9us2jj",
    id: "1282",
    name: "dumbbell incline one arm press on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/ZXDKIKEZoDmXXw",
    id: "0324",
    name: "dumbbell incline palm-in press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/pvyt16setJRRn9",
    id: "1283",
    name: "dumbbell incline press on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/GbzsALwQSWHOBR",
    id: "0328",
    name: "dumbbell incline shoulder raise",
    target: "serratus anterior",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/TrMoqGZqgtvaIW",
    id: "0331",
    name: "dumbbell incline twisted flyes",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/XO6FVZ6lj0LGw8",
    id: "0340",
    name: "dumbbell lying hammer press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/81TXGgMN2XRMUC",
    id: "0343",
    name: "dumbbell lying one arm press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/cozi-H6n1zSXoF",
    id: "0342",
    name: "dumbbell lying one arm press v. 2",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/YsByqmQ6q6Vau4",
    id: "1284",
    name: "dumbbell lying pullover on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/woWm28M11Nx0yg",
    id: "1285",
    name: "dumbbell one arm bench fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/2sU534VLjuNqm0",
    id: "1286",
    name: "dumbbell one arm chest fly on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/KrymZYJYivy1RO",
    id: "1287",
    name: "dumbbell one arm decline chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/a-BsqLLrPaZN8f",
    id: "1288",
    name: "dumbbell one arm fly on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/71Au9FAIMG6jKo",
    id: "1289",
    name: "dumbbell one arm incline chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/3GO3PzBPytqhdN",
    id: "1290",
    name: "dumbbell one arm press on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/eYsk3ES1Ec9993",
    id: "1291",
    name: "dumbbell one arm pullover on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/Z6J-VnQVAaOPgM",
    id: "1622",
    name: "dumbbell one arm reverse grip press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/gqzXlWvOrVdTg2",
    id: "1292",
    name: "dumbbell one leg fly on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/f2qJU4FP0brrKs",
    id: "1293",
    name: "dumbbell press on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/aKdADeVHD4uOA4",
    id: "0375",
    name: "dumbbell pullover",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/LkVbzkkFPBGgrU",
    id: "1294",
    name: "dumbbell pullover hip extension on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/huqxvfydgt8Llv",
    id: "1295",
    name: "dumbbell pullover on exercise ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/H1vIv0i3GFPZZZ",
    id: "1624",
    name: "dumbbell reverse bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/l8YoH597776tWi",
    id: "0433",
    name: "dumbbell straight arm pullover",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/7gHFM5nm6F4WKK",
    id: "1167",
    name: "dynamic chest stretch (male)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "stability ball",
    gifUrl: "https://api.exercisedb.io/image/PgqkR7KgkAk79K",
    id: "1296",
    name: "exercise ball pike push up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "barbell",
    gifUrl: "https://api.exercisedb.io/image/-iflCGex0ggCgh",
    id: "0458",
    name: "floor fly (with barbell)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/Y6dn9JkrS0-e8h",
    id: "3327",
    name: "full planche push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "upper body ergometer",
    gifUrl: "https://api.exercisedb.io/image/A9M0ZmRLn64v30",
    id: "2139",
    name: "hands bike",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "dumbbell",
    gifUrl: "https://api.exercisedb.io/image/W4t55KhF8uqthi",
    id: "3234",
    name: "hyght dumbbell fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/Tty7AS1UpBNE5l",
    id: "0492",
    name: "incline push up depth jump",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/lbCfoG0nTc3npt",
    id: "0493",
    name: "incline push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/Z5mKKOCH0kvK-0",
    id: "3785",
    name: "incline push-up (on box)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/UlCeOyusN0eXJF",
    id: "0494",
    name: "incline reverse grip push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/mvXrM3VrDdkD4z",
    id: "3011",
    name: "incline scapula push up",
    target: "serratus anterior",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/AGj6yK6M6O95Fp",
    id: "1297",
    name: "isometric chest squeeze",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/JQoLwJWATQHdNu",
    id: "0500",
    name: "isometric wipers",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "kettlebell",
    gifUrl: "https://api.exercisedb.io/image/qqvhzs5txiVtEC",
    id: "0519",
    name: "kettlebell alternating press on floor",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "kettlebell",
    gifUrl: "https://api.exercisedb.io/image/f0LMnD1ZI31qbg",
    id: "0531",
    name: "kettlebell extended range one arm press on floor",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "kettlebell",
    gifUrl: "https://api.exercisedb.io/image/o1--Ya997luhxb",
    id: "1298",
    name: "kettlebell one arm floor press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "kettlebell",
    gifUrl: "https://api.exercisedb.io/image/X6VgiptWWrouIf",
    id: "0545",
    name: "kettlebell plyo push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/Ia8UUGQ39ov3ts",
    id: "3211",
    name: "kneeling push-up (male)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/T9LkEGZtn0zkWZ",
    id: "3288",
    name: "korean dips",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/BVX9p-GAtf7TPV",
    id: "0577",
    name: "lever chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/S-ICb3QYPM9Djj",
    id: "0576",
    name: "lever chest press ",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/NY5UlhxzDoxndm",
    id: "1300",
    name: "lever decline chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/ghoIjSfLo9IM6a",
    id: "1299",
    name: "lever incline chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/GF4KZ9KrqLLcUx",
    id: "1479",
    name: "lever incline chest press v. 2",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/vsKieFCCi4ItS-",
    id: "0596",
    name: "lever seated fly",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/2UaBfYWhrCf9uc",
    id: "3758",
    name: "lever standing chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "leverage machine",
    gifUrl: "https://api.exercisedb.io/image/XP46D6rgVAms0N",
    id: "1301",
    name: "machine inner chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "medicine ball",
    gifUrl: "https://api.exercisedb.io/image/Bb1ZcJ01qJLiHp",
    id: "1302",
    name: "medicine ball chest pass",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "medicine ball",
    gifUrl: "https://api.exercisedb.io/image/s6eg38TAYdGtNl",
    id: "1303",
    name: "medicine ball chest push from 3 point stance",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "medicine ball",
    gifUrl: "https://api.exercisedb.io/image/ecimUf7rATrgn2",
    id: "1304",
    name: "medicine ball chest push multiple response",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "medicine ball",
    gifUrl: "https://api.exercisedb.io/image/eGcPyrwbj327IW",
    id: "1305",
    name: "medicine ball chest push single response",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "medicine ball",
    gifUrl: "https://api.exercisedb.io/image/26RdJ5694N-udy",
    id: "1312",
    name: "medicine ball chest push with run release",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/HfZgsBbhPra9Yo",
    id: "3217",
    name: "modified hindu push-up (male)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/OBHpFHm2RohNVJ",
    id: "1306",
    name: "plyo push up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/C50aXCJkVRLEnm",
    id: "1689",
    name: "push and pull bodyweight",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "bosu ball",
    gifUrl: "https://api.exercisedb.io/image/M1kedXP0HtXLej",
    id: "1307",
    name: "push up on bosu ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/Tnk0tUUhoh9289",
    id: "0662",
    name: "push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "bosu ball",
    gifUrl: "https://api.exercisedb.io/image/zk8lGHUZFf8zoo",
    id: "0653",
    name: "push-up (bosu ball)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "stability ball",
    gifUrl: "https://api.exercisedb.io/image/2D9T4t5A18I5fi",
    id: "0655",
    name: "push-up (on stability ball)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "stability ball",
    gifUrl: "https://api.exercisedb.io/image/PNR7j3mfZJVzr8",
    id: "0656",
    name: "push-up (on stability ball)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/PIIqooBeZu-3QU",
    id: "0659",
    name: "push-up (wall)",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/SSnaZme1S29x5s",
    id: "0658",
    name: "push-up (wall) v. 2",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "medicine ball",
    gifUrl: "https://api.exercisedb.io/image/8D2oAVxWh2hOYK",
    id: "0663",
    name: "push-up medicine ball",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/KzHmqDiy4BTrL1",
    id: "3145",
    name: "push-up plus",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/wkxwPKNWHStu4L",
    id: "0666",
    name: "raise single arm push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "resistance band",
    gifUrl: "https://api.exercisedb.io/image/L2xFI0To3jtHYt",
    id: "3124",
    name: "resistance band seated chest press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "roller",
    gifUrl: "https://api.exercisedb.io/image/Fx7bsFaZVL1FLm",
    id: "2203",
    name: "roller seated shoulder flexor depresor retractor",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "roller",
    gifUrl: "https://api.exercisedb.io/image/ti4ptNjxmEvenv",
    id: "2209",
    name: "roller seated single leg shoulder flexor depresor retractor",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/mkqNLOtXdwaYEK",
    id: "3021",
    name: "scapula push-up",
    target: "serratus anterior",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/bI8srYdaJ502wE",
    id: "0699",
    name: "shoulder tap push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/YsyposvhBUlhFY",
    id: "0725",
    name: "single arm push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/N898KeYSZoeCXo",
    id: "0748",
    name: "smith bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/ihDbt8QERmigen",
    id: "0753",
    name: "smith decline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/61zvGahv7LjvLF",
    id: "0754",
    name: "smith decline reverse-grip press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/EU1g8O2xP5UizH",
    id: "0757",
    name: "smith incline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/Ezeugb6BkaUUd-",
    id: "0758",
    name: "smith incline reverse-grip press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/VVTEl4ckNYyki6",
    id: "0759",
    name: "smith incline shoulder raises",
    target: "serratus anterior",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/2ZGLZsrER4rQS8",
    id: "1626",
    name: "smith machine reverse decline close grip bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/qnTJFg4XIJB3Z3",
    id: "0764",
    name: "smith reverse-grip press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/4XNConE2hdnWF1",
    id: "1308",
    name: "smith wide grip bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "smith machine",
    gifUrl: "https://api.exercisedb.io/image/d1LVuKS1qs-yZG",
    id: "1309",
    name: "smith wide grip decline bench press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/1AYWUIS8ytKdYw",
    id: "0803",
    name: "superman push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/FCE8rJ7TKBCcN1",
    id: "0806",
    name: "suspended push-up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "weighted",
    gifUrl: "https://api.exercisedb.io/image/ZLhQIo3xxmtf19",
    id: "1310",
    name: "weighted drop push up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "weighted",
    gifUrl: "https://api.exercisedb.io/image/cqjWzl4WbBipZN",
    id: "3313",
    name: "weighted straight bar dip",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "weighted",
    gifUrl: "https://api.exercisedb.io/image/cZ9sNQX2ZFmOnv",
    id: "0856",
    name: "weighted svend press",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/y1107r9Frs20Jz",
    id: "1311",
    name: "wide hand push up",
    target: "pectorals",
  },
  {
    bodyPart: "chest",
    equipment: "body weight",
    gifUrl: "https://api.exercisedb.io/image/6pWYZNgT4eWAMM",
    id: "2363",
    name: "wide-grip chest dip on high parallel bars",
    target: "pectorals",
  },
];
